# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, Field, conint


class AppStatus(BaseModel):
    health: str | None = None
    instance_id: str | None = None
    last_error: str | None = None
    phase: str | None = None
    restarts: int | None = None


class ErrorResponse(BaseModel):
    error: str | None = None


class ExecReq(BaseModel):
    cmd: list[str] | None = None
    cwd: str | None = None
    env: dict[str, str] | None = None
    timeout_s: int | None = None


class HealthCheck(BaseModel):
    cmd: list[str] | None = None
    healthy_threshold: int | None = None
    interval_s: int | None = None
    path: str | None = None
    port: int | None = None
    start_period_s: int | None = None
    timeout_s: int | None = None
    type: str | None = None
    unhealthy_threshold: int | None = None


class HealthResponse(BaseModel):
    status: str | None = Field(None, examples=['ok'])


class ImageRef(BaseModel):
    oci: str | None = None
    path: str | None = None


class ImageResponse(BaseModel):
    cmd: list[str] | None = None
    content_bytes: int | None = None
    convert_mode: str | None = None
    converted_at_unix_ms: int | None = None
    digest: str | None = None
    entries: int | None = None
    entrypoint: list[str] | None = None
    exposed_ports: list[str] | None = None
    size_bytes: int | None = None
    source_ref: str | None = None


class LogRecord(BaseModel):
    source: str | None = None
    stream: str | None = None
    text: str | None = None
    time_ms: int | None = None


class LogsResponse(BaseModel):
    next_offset: int | None = None
    records: list[LogRecord] | None = None


class NetworkRequest(BaseModel):
    allowlist: list[str] | None = None
    allowlist_cidr: list[str] | None = None
    enabled: bool | None = None
    full_egress: bool | None = None


class NetworkResponse(BaseModel):
    allowlist: list[str] | None = None
    enabled: bool | None = None
    gateway: str | None = None
    guest_ip: str | None = None


class Policy(BaseModel):
    allow_profiles: list[str] | None = None
    max_fork: int | None = None
    max_memory_mib: int | None = None
    max_sandboxes: int | None = None
    max_timeout_s: int | None = None
    max_vcpus: int | None = None
    net_allow_max: list[str] | None = None
    net_full_egress: bool | None = None
    operations: list[str] | None = None


class PortMapping(BaseModel):
    guest_port: int | None = None
    host_ip: str | None = None
    host_port: int | None = None
    protocol: str | None = None


class ProfilesResponse(BaseModel):
    profiles: list[str] | None = None


class PullImageRequest(BaseModel):
    ref: str | None = None


class SandboxResponse(BaseModel):
    created_at: AwareDatetime | None = None
    id: str | None = None
    memory_mib: int | None = None
    network: NetworkResponse | None = None
    profile: str | None = None
    published: list[PortMapping] | None = None
    source_snapshot_id: str | None = None
    vcpus: int | None = None
    workdir: str | None = None


class ServiceStopReq(BaseModel):
    grace_s: int | None = None


class SnapshotResponse(BaseModel):
    created_at: AwareDatetime | None = None
    dir: str | None = None
    id: str | None = None
    mem_path: str | None = None
    memory_mib: int | None = None
    rootfs_path: str | None = None
    source_id: str | None = None
    state_path: str | None = None
    vcpus: int | None = None


class Whoami(BaseModel):
    policy: Policy | None = None
    scoped: bool | None = None


class WireFilesPutResult(BaseModel):
    bytes: int | None = None
    files: int | None = None


class WireResourceUsage(BaseModel):
    context_switches_involuntary: int | None = None
    cpu_sys_ms: int | None = None
    cpu_user_ms: int | None = None
    io_read_bytes: int | None = None
    io_write_bytes: int | None = None
    page_faults_major: int | None = None
    peak_memory_bytes: int | None = None


class WireRestartPolicy(BaseModel):
    max_retries: int | None = None
    policy: str | None = None


class WireServiceSpec(BaseModel):
    cmd: list[str] | None = None
    cwd: str | None = None
    env: dict[str, str] | None = None
    env_exact: bool | None = None
    log_buffer_bytes: int | None = None
    restart: WireRestartPolicy | None = None
    stop_grace_s: int | None = None
    stop_signal: str | None = None
    user: str | None = None


class AppResponse(BaseModel):
    created_at: AwareDatetime | None = None
    desired_state: str | None = None
    disk_bytes: int | None = None
    env: dict[str, str] | None = None
    generation: conint(ge=0) | None = None
    health: HealthCheck | None = None
    id: str | None = None
    image: ImageRef | None = None
    memory_mib: int | None = None
    name: str | None = None
    network: NetworkRequest | None = None
    publish: list[PortMapping] | None = None
    publish_all: bool | None = None
    pull: str | None = None
    restart: WireRestartPolicy | None = None
    service: WireServiceSpec | None = None
    status: AppStatus | None = None
    updated_at: AwareDatetime | None = None
    vcpus: int | None = None


class ConfigureServiceReq(BaseModel):
    cmd: list[str] | None = None
    cwd: str | None = None
    env: dict[str, str] | None = None
    env_exact: bool | None = None
    log_buffer_bytes: int | None = None
    restart: WireRestartPolicy | None = None
    stop_grace_s: int | None = None
    stop_signal: str | None = None
    user: str | None = None


class CreateAppRequest(BaseModel):
    desired_state: str | None = None
    disk_bytes: int | None = None
    env: dict[str, str] | None = None
    health: HealthCheck | None = None
    image: ImageRef | None = None
    memory_mib: int | None = None
    name: str | None = None
    network: NetworkRequest | None = None
    publish: list[PortMapping] | None = None
    publish_all: bool | None = None
    pull: str | None = None
    restart: WireRestartPolicy | None = None
    service: WireServiceSpec | None = None
    vcpus: int | None = None


class CreateSandboxRequest(BaseModel):
    boot_args: str | None = None
    disk_bytes: int | None = None
    image: ImageRef | None = None
    memory_mib: int | None = None
    network: NetworkRequest | None = None
    profile: str | None = None
    publish: list[PortMapping] | None = None
    publish_all: bool | None = None
    pull: str | None = None
    service: WireServiceSpec | None = None
    timeout_s: int | None = None
    vcpus: int | None = None


class ForkReq(BaseModel):
    count: int | None = None
    publish: list[PortMapping] | None = None


class ForkResponse(BaseModel):
    sandboxes: list[SandboxResponse] | None = None


class ImageListResponse(BaseModel):
    images: list[ImageResponse] | None = None


class ListResponse(BaseModel):
    sandboxes: list[SandboxResponse] | None = None


class SnapshotListResponse(BaseModel):
    snapshots: list[SnapshotResponse] | None = None


class UpdateAppReq(BaseModel):
    disk_bytes: int | None = None
    env: dict[str, str] | None = None
    health: HealthCheck | None = None
    image: ImageRef | None = None
    memory_mib: int | None = None
    name: str | None = None
    network: NetworkRequest | None = None
    publish: list[PortMapping] | None = None
    publish_all: bool | None = None
    pull: str | None = None
    restart: WireRestartPolicy | None = None
    service: WireServiceSpec | None = None
    vcpus: int | None = None


class WireExecResult(BaseModel):
    duration_ms: int | None = None
    error: str | None = None
    exit_code: int | None = None
    oom_killed: bool | None = None
    signal: str | None = None
    timed_out: bool | None = None
    usage: WireResourceUsage | None = None


class WireServiceStatus(BaseModel):
    last_exit: WireExecResult | None = None
    last_exit_at_unix_ms: int | None = None
    last_exit_requested: bool | None = None
    live_peak_rss_bytes: int | None = None
    live_rss_bytes: int | None = None
    log_dropped_bytes: conint(ge=0) | None = None
    log_first_seq: conint(ge=0) | None = None
    log_next_seq: conint(ge=0) | None = None
    pid: int | None = None
    restarts: int | None = None
    spec: WireServiceSpec | None = None
    started_at_unix_ms: int | None = None
    state: str | None = None
    uptime_ms: int | None = None


class AppListResponse(BaseModel):
    apps: list[AppResponse] | None = None
