/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List apps */
        get: operations["listApps"];
        put?: never;
        /**
         * Create a durable app
         * @description Creates a named app the daemon keeps a healthy instance of, re-creating it from spec after a daemon restart. desired_state defaults to "running". The instance boots asynchronously; the response is the app's initial state.
         */
        post: operations["createApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an app
         * @description Desired state plus observed status (instance id, phase, health, restarts).
         */
        get: operations["getApp"];
        /**
         * Update an app
         * @description Replaces the app's spec (name immutable) and redeploys its instance from the new spec — the daemon bumps the app's generation and the reconciler destroys the old instance and boots a fresh one. Desired running/stopped is retained.
         */
        put: operations["updateApp"];
        post?: never;
        /**
         * Delete an app
         * @description Removes the app and tears down its instance on the next reconcile.
         */
        delete: operations["deleteApp"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{name}/exec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Interactive exec into an app (WebSocket)
         * @description WebSocket interactive exec against the app's current instance; identical contract to GET /sandboxes/{id}/exec. 409 when the app has no running instance.
         */
        get: operations["appExecWS"];
        put?: never;
        /**
         * Run a command in an app's current instance (streams frames)
         * @description Resolves the app to its current instance and runs the command there, streaming the same length-prefixed frame protocol as POST /sandboxes/{id}/exec (?stdin=1 for a hijacked interactive session). Resolution is per-request, so it targets whatever instance is current across a self-heal or rolling update. 409 when the app has no running instance.
         */
        post: operations["appExec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/apps/{name}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read an app's current-instance logs
         * @description Durable logs (service output + exec activity) of the app's current instance; same shape as GET /sandboxes/{id}/logs. 409 when the app has no running instance, 501 with no log store.
         */
        get: operations["appLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Always returns 200 and is exempt from auth, so probes work without a key.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cached images */
        get: operations["listImages"];
        put?: never;
        /**
         * Pull and convert an OCI image
         * @description Experimental. Pulls a registry image and converts it to a bootable rootfs. Returns 501 when image support is not enabled (set --image-dir).
         */
        post: operations["pullImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a docker-save archive
         * @description Experimental. Imports an image from a docker-save tar on the request body (application/octet-stream); ?tag selects one image in a multi-image archive.
         */
        post: operations["importImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a cached image */
        get: operations["getImage"];
        put?: never;
        post?: never;
        /** Delete a cached image */
        delete: operations["deleteImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List rootfs profiles
         * @description The rootfs profiles the daemon can boot sandboxes from.
         */
        get: operations["listProfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registry/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List registry credentials
         * @description Lists stored registry credentials as host + username only — never the secret.
         */
        get: operations["listRegistryCredentials"];
        put?: never;
        /**
         * Store a private-registry credential
         * @description Adds or replaces the credential used to pull from a private registry (`crucible registry login`). The secret is write-only — it is never returned by any endpoint. 501 when no credential store is configured.
         */
        post: operations["registryLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registry/credentials/{host}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a registry credential
         * @description Deletes the stored credential for a registry host (`crucible registry logout`).
         */
        delete: operations["registryLogout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sandboxes */
        get: operations["listSandboxes"];
        put?: never;
        /**
         * Create a sandbox
         * @description Boots a Firecracker microVM. All fields are optional; an empty body uses the daemon defaults. `image` boots from a converted OCI image (pulled on demand — see the images endpoints); a daemon without an image store answers 501.
         */
        post: operations["createSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a sandbox */
        get: operations["getSandbox"];
        put?: never;
        post?: never;
        /** Destroy a sandbox */
        delete: operations["deleteSandbox"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{id}/exec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Interactive exec (WebSocket)
         * @description WebSocket upgrade for a full-duplex interactive exec. The client's first message is the JSON ExecRequest; after that, the concatenated binary message payloads in each direction form exactly the same length-prefixed frame stream as POST ?stdin=1 (stdin/stdin_close up, stdout/stderr/exit down). Frames may split across messages — decode the concatenated stream. Non-WebSocket GETs answer 426.
         */
        get: operations["execSandboxWS"];
        put?: never;
        /**
         * Run a command (streams frames)
         * @description Runs a command in the guest and streams the result as length-prefixed frames ([type:1][reserved:3][size:4 BE][payload]) where type is stdout, stderr, or exit; the exit payload is a JSON ExecResult. Set ?stdin=1 for a hijacked, full-duplex interactive exec.
         */
        post: operations["execSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a single guest file
         * @description Returns the raw bytes of one guest file (?path), capped at ?max_bytes. Content only, guest → host; nothing is written host-side.
         */
        get: operations["getFile"];
        put?: never;
        /**
         * Push files into a sandbox
         * @description Extracts a tar stream (the request body, application/octet-stream) beneath ?path in the guest filesystem; the `crucible cp` push path. Rejects entries that escape the destination.
         */
        post: operations["putFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read durable sandbox logs
         * @description Durable per-sandbox logs (service output + exec activity) that survive the sandbox. Returns 501 when the daemon has no log store configured.
         */
        get: operations["sandboxLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{id}/service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service status */
        get: operations["serviceStatus"];
        /**
         * Configure the supervised service
         * @description Experimental. Sets and (re)starts the guest's supervised long-lived entrypoint.
         */
        put: operations["configureService"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{id}/service/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream service logs
         * @description Experimental. Streams the supervised service's stdout/stderr as it is produced.
         */
        get: operations["serviceLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{id}/service/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart the service */
        post: operations["restartService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{id}/service/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start the service */
        post: operations["startService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{id}/service/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop the service */
        post: operations["stopService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandboxes/{id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snapshot a sandbox */
        post: operations["createSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List snapshots */
        get: operations["listSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a snapshot */
        get: operations["getSnapshot"];
        put?: never;
        post?: never;
        /** Delete a snapshot */
        delete: operations["deleteSnapshot"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{id}/fork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fork sandboxes from a snapshot
         * @description Creates count sandboxes from the snapshot (query param or body; body wins). All-or-nothing: a mid-fork failure rolls back. The optional body's publish maps host ports onto the fork (docker -p semantics); publish requires count 1 because host ports are exclusive.
         */
        post: operations["forkSnapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/volumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List volumes */
        get: operations["listVolumes"];
        put?: never;
        /**
         * Create a persistent volume
         * @description Creates a durable block-device volume (formatted ext4 on first use). Returns 501 when volume storage is not enabled (set --volume-dir), 409 when the name already exists.
         */
        post: operations["createVolume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/volumes/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a volume */
        get: operations["getVolume"];
        put?: never;
        post?: never;
        /**
         * Delete a volume
         * @description Deletes the volume and its data. 409 when it is attached to a live sandbox.
         */
        delete: operations["deleteVolume"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Effective policy for the caller
         * @description Reports whether the token is scoped and, if so, the policy the daemon enforces for it.
         */
        get: operations["whoami"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppExecReq: {
            cmd?: string[] | null;
            cwd?: string;
            env?: {
                [key: string]: string;
            };
            timeout_s?: number;
        };
        AppListResponse: {
            apps?: components["schemas"]["AppResponse"][] | null;
        };
        AppResponse: {
            can_call?: string[];
            /** Format: date-time */
            created_at?: string;
            desired_state?: string;
            /** Format: int64 */
            disk_bytes?: number;
            env?: {
                [key: string]: string;
            };
            generation?: number;
            health?: components["schemas"]["HealthCheck"];
            id?: string;
            image?: components["schemas"]["ImageRef"];
            memory_mib?: number;
            name?: string;
            network?: components["schemas"]["NetworkRequest"];
            port?: number;
            publish?: components["schemas"]["PortMapping"][];
            publish_all?: boolean;
            pull?: string;
            restart?: components["schemas"]["WireRestartPolicy"];
            service?: components["schemas"]["WireServiceSpec"];
            sleep?: components["schemas"]["SleepPolicy"];
            status?: components["schemas"]["AppStatus"];
            /** Format: date-time */
            updated_at?: string;
            vcpus?: number;
            volumes?: components["schemas"]["VolumeMount"][];
        };
        AppStatus: {
            health?: string;
            instance_generation?: number;
            instance_id?: string;
            instances?: components["schemas"]["InstanceStatus"][];
            last_error?: string;
            /** Format: int64 */
            last_wake_latency_ms?: number;
            phase?: string;
            ready_replicas?: number;
            replicas?: number;
            restarts?: number;
            sleep_count?: number;
        };
        ConfigureServiceReq: {
            cmd?: string[] | null;
            cwd?: string;
            env?: {
                [key: string]: string;
            };
            env_exact?: boolean;
            log_buffer_bytes?: number;
            restart?: components["schemas"]["WireRestartPolicy"];
            stop_grace_s?: number;
            stop_signal?: string;
            user?: string;
        };
        CreateAppRequest: {
            can_call?: string[];
            desired_state?: string;
            /** Format: int64 */
            disk_bytes?: number;
            env?: {
                [key: string]: string;
            };
            health?: components["schemas"]["HealthCheck"];
            image?: components["schemas"]["ImageRef"];
            memory_mib?: number;
            name?: string;
            network?: components["schemas"]["NetworkRequest"];
            port?: number;
            publish?: components["schemas"]["PortMapping"][];
            publish_all?: boolean;
            pull?: string;
            restart?: components["schemas"]["WireRestartPolicy"];
            service?: components["schemas"]["WireServiceSpec"];
            sleep?: components["schemas"]["SleepPolicy"];
            vcpus?: number;
            volumes?: components["schemas"]["VolumeMount"][];
        };
        CreateSandboxRequest: {
            boot_args?: string;
            /** Format: int64 */
            disk_bytes?: number;
            image?: components["schemas"]["ImageRef"];
            memory_mib?: number;
            network?: components["schemas"]["NetworkRequest"];
            profile?: string;
            publish?: components["schemas"]["PortMapping"][];
            publish_all?: boolean;
            pull?: string;
            registry_auth?: components["schemas"]["RegistryAuth"];
            service?: components["schemas"]["WireServiceSpec"];
            timeout_s?: number;
            vcpus?: number;
            volumes?: components["schemas"]["VolumeMount"][];
        };
        CreateVolumeRequest: {
            name?: string;
            /** Format: int64 */
            size_bytes?: number;
        };
        ErrorResponse: {
            error?: string;
        };
        ExecReq: {
            cmd?: string[] | null;
            cwd?: string;
            env?: {
                [key: string]: string;
            };
            timeout_s?: number;
        };
        ForkReq: {
            count?: number;
            publish?: components["schemas"]["PortMapping"][];
        };
        ForkResponse: {
            sandboxes?: components["schemas"]["SandboxResponse"][] | null;
        };
        HealthCheck: {
            cmd?: string[];
            healthy_threshold?: number;
            interval_s?: number;
            path?: string;
            port?: number;
            start_period_s?: number;
            timeout_s?: number;
            type?: string;
            unhealthy_threshold?: number;
        };
        HealthResponse: {
            /** @example ok */
            status?: string;
        };
        ImageListResponse: {
            images?: components["schemas"]["ImageResponse"][] | null;
        };
        ImageRef: {
            oci?: string;
            path?: string;
        };
        ImageResponse: {
            cmd?: string[];
            /** Format: int64 */
            content_bytes?: number;
            convert_mode?: string;
            /** Format: int64 */
            converted_at_unix_ms?: number;
            digest?: string;
            entries?: number;
            entrypoint?: string[];
            exposed_ports?: string[];
            /** Format: int64 */
            size_bytes?: number;
            source_ref?: string;
        };
        InstanceStatus: {
            generation?: number;
            health?: string;
            instance_id?: string;
        };
        ListResponse: {
            sandboxes?: components["schemas"]["SandboxResponse"][] | null;
        };
        LogRecord: {
            source?: string;
            stream?: string;
            text?: string;
            /** Format: int64 */
            time_ms?: number;
        };
        LogsResponse: {
            /** Format: int64 */
            next_offset?: number;
            records?: components["schemas"]["LogRecord"][] | null;
        };
        NetworkRequest: {
            allowlist?: string[];
            allowlist_cidr?: string[];
            enabled?: boolean;
            full_egress?: boolean;
        };
        NetworkResponse: {
            allowlist?: string[];
            enabled?: boolean;
            gateway?: string;
            guest_ip?: string;
        };
        Policy: {
            allow_profiles?: string[];
            max_fork?: number;
            max_memory_mib?: number;
            max_sandboxes?: number;
            max_timeout_s?: number;
            max_vcpus?: number;
            net_allow_max?: string[] | null;
            net_full_egress?: boolean;
            operations?: string[];
        };
        PortMapping: {
            guest_port?: number;
            host_ip?: string;
            host_port?: number;
            protocol?: string;
        };
        ProfilesResponse: {
            profiles?: string[] | null;
        };
        PullImageRequest: {
            ref?: string;
            registry_auth?: components["schemas"]["RegistryAuth"];
        };
        RegistryAuth: {
            secret?: string;
            username?: string;
        };
        RegistryCredential: {
            /** Format: date-time */
            created_at?: string;
            host?: string;
            username?: string;
        };
        RegistryCredentialListResponse: {
            registries?: components["schemas"]["RegistryCredential"][] | null;
        };
        RegistryCredentialRequest: {
            host?: string;
            secret?: string;
            username?: string;
        };
        SandboxResponse: {
            /** Format: date-time */
            created_at?: string;
            id?: string;
            memory_mib?: number;
            network?: components["schemas"]["NetworkResponse"];
            profile?: string;
            published?: components["schemas"]["PortMapping"][];
            source_snapshot_id?: string;
            vcpus?: number;
            workdir?: string;
        };
        ServiceStopReq: {
            grace_s?: number;
        };
        SleepPolicy: {
            idle_timeout_s?: number;
            max_scale?: number;
            min_scale?: number;
            target_concurrency?: number;
        };
        SnapshotListResponse: {
            snapshots?: components["schemas"]["SnapshotResponse"][] | null;
        };
        SnapshotResponse: {
            /** Format: date-time */
            created_at?: string;
            dir?: string;
            id?: string;
            mem_path?: string;
            memory_mib?: number;
            rootfs_path?: string;
            source_id?: string;
            state_path?: string;
            vcpus?: number;
        };
        UpdateAppReq: {
            can_call?: string[];
            /** Format: int64 */
            disk_bytes?: number;
            env?: {
                [key: string]: string;
            };
            health?: components["schemas"]["HealthCheck"];
            image?: components["schemas"]["ImageRef"];
            memory_mib?: number;
            name?: string;
            network?: components["schemas"]["NetworkRequest"];
            port?: number;
            publish?: components["schemas"]["PortMapping"][];
            publish_all?: boolean;
            pull?: string;
            restart?: components["schemas"]["WireRestartPolicy"];
            service?: components["schemas"]["WireServiceSpec"];
            sleep?: components["schemas"]["SleepPolicy"];
            vcpus?: number;
            volumes?: components["schemas"]["VolumeMount"][];
        };
        Volume: {
            attached_to?: string;
            /** Format: date-time */
            created_at?: string;
            host_id?: string;
            name?: string;
            /** Format: int64 */
            size_bytes?: number;
        };
        VolumeListResponse: {
            volumes?: components["schemas"]["Volume"][] | null;
        };
        VolumeMount: {
            name?: string;
            path?: string;
        };
        Whoami: {
            policy?: components["schemas"]["Policy"];
            scoped?: boolean;
        };
        WireExecResult: {
            /** Format: int64 */
            duration_ms?: number;
            error?: string;
            exit_code?: number;
            oom_killed?: boolean;
            signal?: string;
            timed_out?: boolean;
            usage?: components["schemas"]["WireResourceUsage"];
        };
        WireFilesPutResult: {
            /** Format: int64 */
            bytes?: number;
            files?: number;
        };
        WireResourceUsage: {
            /** Format: int64 */
            context_switches_involuntary?: number;
            /** Format: int64 */
            cpu_sys_ms?: number;
            /** Format: int64 */
            cpu_user_ms?: number;
            /** Format: int64 */
            io_read_bytes?: number;
            /** Format: int64 */
            io_write_bytes?: number;
            /** Format: int64 */
            page_faults_major?: number;
            /** Format: int64 */
            peak_memory_bytes?: number;
        };
        WireRestartPolicy: {
            max_retries?: number;
            policy?: string;
        };
        WireServiceSpec: {
            cmd?: string[] | null;
            cwd?: string;
            env?: {
                [key: string]: string;
            };
            env_exact?: boolean;
            log_buffer_bytes?: number;
            restart?: components["schemas"]["WireRestartPolicy"];
            stop_grace_s?: number;
            stop_signal?: string;
            user?: string;
        };
        WireServiceStatus: {
            last_exit?: components["schemas"]["WireExecResult"];
            /** Format: int64 */
            last_exit_at_unix_ms?: number;
            last_exit_requested?: boolean;
            /** Format: int64 */
            live_peak_rss_bytes?: number;
            /** Format: int64 */
            live_rss_bytes?: number;
            log_dropped_bytes?: number;
            log_first_seq?: number;
            log_next_seq?: number;
            pid?: number;
            restarts?: number;
            spec?: components["schemas"]["WireServiceSpec"];
            /** Format: int64 */
            started_at_unix_ms?: number;
            state?: string;
            /** Format: int64 */
            uptime_ms?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listApps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppListResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createApp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateAppRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description App name (a DNS label, e.g. web). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description App name (a DNS label, e.g. web). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateAppReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description App name (a DNS label, e.g. web). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    appExecWS: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description App name (a DNS label, e.g. web). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    appExec: {
        parameters: {
            query?: {
                /** @description Set to "1" for an interactive, full-duplex exec (hijacked stream). */
                stdin?: string;
            };
            header?: never;
            path: {
                /** @description App name (a DNS label, e.g. web). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AppExecReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    appLogs: {
        parameters: {
            query?: {
                /** @description Byte offset to read from; -1 (default) tails the recent log. */
                since?: number;
                /** @description Filter by source: service | exec | all (default all). */
                source?: string;
            };
            header?: never;
            path: {
                /** @description App name (a DNS label, e.g. web). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listImages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageListResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    pullImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PullImageRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    importImage: {
        parameters: {
            query?: {
                /** @description Which image inside a multi-image docker-save archive to import. */
                tag?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Image reference (nginx:alpine) or converted digest. */
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Image reference (nginx:alpine) or converted digest. */
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilesResponse"];
                };
            };
        };
    };
    listRegistryCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistryCredentialListResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registryLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RegistryCredentialRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registryLogout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Registry host, e.g. ghcr.io or index.docker.io. */
                host: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listSandboxes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse"];
                };
            };
        };
    };
    createSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateSandboxRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sandbox ID, e.g. sbx_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sandbox ID, e.g. sbx_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    execSandboxWS: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sandbox ID, e.g. sbx_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    execSandbox: {
        parameters: {
            query?: {
                /** @description Set to "1" for an interactive, full-duplex exec (hijacked stream). */
                stdin?: string;
            };
            header?: never;
            path: {
                /** @description Sandbox ID, e.g. sbx_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ExecReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getFile: {
        parameters: {
            query: {
                /** @description Guest file path to read. */
                path: string;
                /** @description Cap on bytes returned (default 10 MiB). */
                max_bytes?: number;
            };
            header?: never;
            path: {
                /** @description Sandbox ID, e.g. sbx_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    putFiles: {
        parameters: {
            query: {
                /** @description Guest destination directory the tar is extracted beneath. */
                path: string;
            };
            header?: never;
            path: {
                /** @description Sandbox ID, e.g. sbx_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WireFilesPutResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    sandboxLogs: {
        parameters: {
            query?: {
                /** @description Byte offset to read from; -1 (default) tails the recent log. */
                since?: number;
                /** @description Filter by source: service | exec | all (default all). */
                source?: string;
            };
            header?: never;
            path: {
                /** @description Sandbox ID, e.g. sbx_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    serviceStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sandbox ID, e.g. sbx_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WireServiceStatus"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    configureService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sandbox ID, e.g. sbx_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConfigureServiceReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WireServiceStatus"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    serviceLogs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sandbox ID, e.g. sbx_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    restartService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sandbox ID, e.g. sbx_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WireServiceStatus"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sandbox ID, e.g. sbx_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WireServiceStatus"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stopService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sandbox ID, e.g. sbx_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ServiceStopReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WireServiceStatus"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sandbox ID, e.g. sbx_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotListResponse"];
                };
            };
        };
    };
    getSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Snapshot ID, e.g. snap_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Snapshot ID, e.g. snap_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    forkSnapshot: {
        parameters: {
            query?: {
                /** @description Number of sandboxes to fork (default 1). The body's count wins when both are set. */
                count?: number;
            };
            header?: never;
            path: {
                /** @description Snapshot ID, e.g. snap_ab12cd34. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ForkReq"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForkResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listVolumes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumeListResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createVolume: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateVolumeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Volume"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getVolume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Volume name ([a-z0-9][a-z0-9-]*). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Volume"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteVolume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Volume name ([a-z0-9][a-z0-9-]*). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    whoami: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Whoami"];
                };
            };
        };
    };
}
