// Named aliases over the generated schema (schema.gen.ts, regenerated by
// `make gen-ts`) so user code imports readable names instead of indexing
// components["schemas"]. Add aliases here as the surface grows; never edit
// schema.gen.ts itself.
import type { components } from "./schema.gen.ts";

type S = components["schemas"];

export type CreateSandboxRequest = S["CreateSandboxRequest"];
export type SandboxResponse = S["SandboxResponse"];
export type SnapshotResponse = S["SnapshotResponse"];
export type ImageRef = S["ImageRef"];
export type ImageResponse = S["ImageResponse"];
export type PullImageRequest = S["PullImageRequest"];
export type LogsResponse = S["LogsResponse"];
export type LogRecord = S["LogRecord"];
export type ProfilesResponse = S["ProfilesResponse"];
export type ErrorResponse = S["ErrorResponse"];
export type Whoami = S["Whoami"];
export type ExecRequest = S["ExecReq"];
export type ExecResult = S["WireExecResult"];
export type ResourceUsage = S["WireResourceUsage"];
export type ServiceSpec = S["WireServiceSpec"];
export type ServiceStatus = S["WireServiceStatus"];
export type FilesPutResult = S["WireFilesPutResult"];

/**
 * One page of a list. The daemon returns everything in a single page today;
 * nextCursor is reserved for a future control-plane (mirrors the Go SDK's
 * Page[T]).
 */
export interface Page<T> {
  items: T[];
  nextCursor?: string;
}
